"""Original procedural HAVAL H9 interpretation. Blender 5.x, metre units.
Built from the eight supplied photographs; no source vehicle meshes.
Blender: front -Y, up +Z, vehicle left +X. GLB: front +Z, up +Y.
"""
import bpy, math, bmesh, json
from mathutils import Vector, Matrix
from math import sin, cos, pi

bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for d in list(bpy.data.materials): bpy.data.materials.remove(d)
sc=bpy.context.scene
sc.name='H9_Vehicle'
sc.unit_settings.system='METRIC'
sc.unit_settings.scale_length=1.0
groups={}

def linear(v):
    v=v/255
    return v/12.92 if v<=.04045 else ((v+.055)/1.055)**2.4
def mat(name,h,metal=0,rough=.5,emission=0):
    m=bpy.data.materials.new(name)
    m.diffuse_color=tuple(linear(int(h[i:i+2],16)) for i in (0,2,4))+(1,)
    m.use_nodes=True
    p=m.node_tree.nodes.get('Principled BSDF')
    p.inputs['Base Color'].default_value=m.diffuse_color
    p.inputs['Metallic'].default_value=metal
    p.inputs['Roughness'].default_value=rough
    p.inputs['Coat Weight'].default_value=0
    if emission:
        p.inputs['Emission Color'].default_value=m.diffuse_color
        p.inputs['Emission Strength'].default_value=emission
    return m
M={
 'paint':mat('Mat_Body_MatteGrey','626467',.16,.66),
 'glass':mat('Mat_Glass','151d24',.10,.25),
 'rubber':mat('Mat_Rubber','151718',0,.85),
 'rim':mat('Mat_Rim_Gunmetal','737b84',.46,.39),
 'trim':mat('Mat_DarkTrim','252a2d',.12,.58),
 'head':mat('Mat_Headlight','dfeef2',.12,.28,.18),
 'tail':mat('Mat_Taillight','a61727',.1,.3,.12),
 'plate':mat('Mat_LicensePlate','eeefeb',0,.6)
}

def empty(name,loc=(0,0,0),parent=None):
    o=bpy.data.objects.new(name,None); sc.collection.objects.link(o)
    o.location=loc; o.parent=parent; o.empty_display_size=.13
    return o
root=empty('H9_Root')
root['forward_axis_blender']='-Y'; root['forward_axis_glTF']='+Z'
root['up_axis_glTF']='+Y'; root['units']='metres'
root['road_wheel_radius']=.42432; root['wheelbase']=2.85
root['source']='Original geometry authored from supplied H9 reference images'
root['license_plate_text']='blank; generated by game at runtime'

def mesh(name,v,f,material,group=None,smooth=False):
    me=bpy.data.meshes.new(name+'_Mesh'); me.from_pydata(v,[],f); me.update()
    o=bpy.data.objects.new(name,me); sc.collection.objects.link(o)
    o.data.materials.append(M[material] if isinstance(material,str) else material)
    bm=bmesh.new(); bm.from_mesh(me); bmesh.ops.recalc_face_normals(bm,faces=bm.faces); bm.to_mesh(me); bm.free()
    for p in me.polygons:p.use_smooth=smooth
    if group:groups.setdefault(group,[]).append(o)
    return o

def apply(o,mod):
    bpy.context.view_layer.objects.active=o
    bpy.ops.object.modifier_apply(modifier=mod.name)

def bevel(o,w=.02,seg=3):
    b=o.modifiers.new('Controlled bevel','BEVEL'); b.width=min(w,min(d for d in o.dimensions if d>0)*.44); b.segments=min(seg,2)
    apply(o,b)
    for p in o.data.polygons:p.use_smooth=True
    n=o.modifiers.new('Weighted surface normals','WEIGHTED_NORMAL'); n.keep_sharp=True; n.weight=50
    apply(o,n)
    return o

def box(name,loc,dims,material,bev=.02,group=None,seg=3):
    x,y,z=(a/2 for a in dims)
    v=[(a*x,b*y,c*z) for a,b,c in [(-1,-1,-1),(1,-1,-1),(1,1,-1),(-1,1,-1),(-1,-1,1),(1,-1,1),(1,1,1),(-1,1,1)]]
    f=[(3,2,1,0),(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7),(4,5,6,7)]
    o=mesh(name,v,f,material,group);o.location=loc
    if bev:bevel(o,bev,1 if group=='H9_Trim' or bev<.018 else seg)
    return o

def prism(name,poly,axis,lo,hi,material,group=None,bev=0,seg=3):
    def p(a,b,t):
        return (t,a,b) if axis=='X' else ((a,t,b) if axis=='Y' else (a,b,t))
    v=[p(a,b,t) for t in (lo,hi) for a,b in poly];n=len(poly)
    f=[tuple(range(n-1,-1,-1)),tuple(range(n,2*n))]
    f += [(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]
    o=mesh(name,v,f,material,group)
    if bev:bevel(o,bev,1 if group=='H9_Trim' or bev<.018 else seg)
    return o

def tube(name,path,r,material,group,sides=8,closed=False):
    pts=[Vector(x) for x in path];v=[];f=[];N=len(pts)
    for i,p in enumerate(pts):
        t=(pts[(i+1)%N]-pts[i-1]).normalized() if closed or 0<i<N-1 else ((pts[1]-pts[0]).normalized() if i==0 else (pts[-1]-pts[-2]).normalized())
        ref=Vector((1,0,0)) if abs(t.x)<.85 else Vector((0,1,0))
        u=t.cross(ref).normalized();w=t.cross(u).normalized()
        for k in range(sides):v.append(tuple(p+r*(cos(k*2*pi/sides)*u+sin(k*2*pi/sides)*w)))
    for i in range(N if closed else N-1):
        j=(i+1)%N
        for k in range(sides):f.append((i*sides+k,i*sides+(k+1)%sides,j*sides+(k+1)%sides,j*sides+k))
    if not closed:f.extend([tuple(range(sides-1,-1,-1)),tuple((N-1)*sides+k for k in range(sides))])
    return mesh(name,v,f,material,group,True)

def rr(w,h,r,n=6):
    p=[]
    for cx,cy,a in [(w/2-r,h/2-r,0),(-w/2+r,h/2-r,90),(-w/2+r,-h/2+r,180),(w/2-r,-h/2+r,270)]:
        for i in range(n+1):
            t=math.radians(a+i*90/n);p.append((cx+r*cos(t),cy+r*sin(t)))
    return p

def ring(name,profile,center,axis,material,group,N=64):
    v=[];f=[]
    for axial,r in profile:
        for k in range(N):
            a=k*2*pi/N
            t=(axial,r*cos(a),r*sin(a)) if axis=='X' else (r*cos(a),axial,r*sin(a))
            v.append(tuple(center[i]+t[i] for i in range(3)))
    for j in range(len(profile)):
        q=(j+1)%len(profile)
        for k in range(N):f.append((j*N+k,j*N+(k+1)%N,q*N+(k+1)%N,q*N+k))
    return mesh(name,v,f,material,group,True)

# Lower body: shaped cross-sections, not a decimated/downloaded mesh.
stations=[(-2.30,.915,.48,1.30),(-2.20,.953,.435,1.335),(-1.94,.968,.422,1.34),(-.75,.974,.425,1.35),(-.53,.975,.428,1.315),(1.91,.958,.44,1.315),(2.19,.933,.48,1.29)]
v=[];f=[]
for y,w,l,t in stations:
    profile=[(-w*.89,l),(w*.89,l),(w*.985,l+.095),(w,t-.17),(w*.979,t-.045),(w*.895,t),(-w*.895,t),(-w*.979,t-.045),(-w,t-.17),(-w*.985,l+.095)]
    v.extend((x,y,z) for x,z in profile)
for i in range(len(stations)-1):
    for j in range(10):f.append((i*10+j,i*10+(j+1)%10,(i+1)*10+(j+1)%10,(i+1)*10+j))
f.extend([tuple(range(9,-1,-1)),tuple((len(stations)-1)*10+j for j in range(10))])
body=mesh('Body shaped shell',v,f,'paint','H9_BodyPaint')

# Squared arched openings with rounded corners, cut only through side sections.
arch=[(-.627,-.08),(.627,-.08),(.627,.43),(.542,.77),(.454,.958),(.337,1.041),(-.337,1.041),(-.454,.958),(-.542,.77),(-.627,.43)]
arch=[(a,.425+(b-.425)*.935 if b>.425 else b) for a,b in arch]
for y in (-1.44,1.41):
    for s in (-1,1):
        cut=prism('Temporary wheel clearance',[(a+y,b) for a,b in arch],'X',s*.98-.52,s*.98+.52,'trim',bev=.055,seg=5)
        mod=body.modifiers.new('Wheel well','BOOLEAN');mod.operation='DIFFERENCE';mod.object=cut
        apply(body,mod);bpy.data.objects.remove(cut,do_unlink=True)
bevel(body,.028,3)

def rounded_path(points,steps=5,factor=.16):
    out=[points[0]]
    for i in range(1,len(points)-1):
        a,b,c=map(Vector,(points[i-1],points[i],points[i+1]));u=b+(a-b)*factor;v=b+(c-b)*factor
        for k in range(steps+1):
            t=k/steps;out.append(tuple((1-t)**2*u+2*(1-t)*t*b+t*t*v))
    out.append(points[-1]);return out

# Fender lips follow the same squared arch. Their upper section is broad and softly crowned.
pa=[(-.627,.425),(-.542,.77),(-.454,.958),(-.337,1.041),(.337,1.041),(.454,.958),(.542,.77),(.627,.425)]
pa=[(a,.425+(b-.425)*.935) for a,b in pa]
pa=rounded_path(pa,3,.25)
for y in (-1.44,1.41):
    for s in (-1,1):
        verts=[];faces=[];n=len(pa)
        for i,(a,z) in enumerate(pa):
            prev=Vector(pa[max(0,i-1)]);nxt=Vector(pa[min(n-1,i+1)]);t=(nxt-prev).normalized();normal=Vector((-t.y,t.x))
            for d,x in [(0,.993),(.017,1.008),(.045,1.006),(.084,.982),(.098,.959)]:
                verts.append((s*x,y+a+d*normal.x,z+d*normal.y))
        for i in range(n-1):
            for k in range(4):faces.append((i*5+k,(i+1)*5+k,(i+1)*5+k+1,i*5+k+1))
        # Close the underside of this thin curved shell, not an open ribbon.
        L=len(verts);verts += [(x-s*.012,a,z) for x,a,z in verts]
        faces += [tuple(j+L for j in reversed(face)) for face in list(faces)]
        boundary=[i*5 for i in range(n)]+[(n-1)*5+j for j in range(1,5)]+[i*5+4 for i in range(n-2,-1,-1)]+[j for j in range(3,0,-1)]
        for a,b in zip(boundary,boundary[1:]+boundary[:1]):faces.append((a,b,b+L,a+L))
        mesh('Sculpted painted arch',verts,faces,'paint','H9_BodyPaint',True)
        tube('Arch inner gasket',[(s*.987,y+a,z-.008) for a,z in pa],.010,'trim','H9_Trim',8)
        # Dark inside well, curved rather than a visible flat backing disk.
        ringpath=[(s*.607,y+a,z-.018) for a,z in pa]
        # Wheel-well cut faces already supply the dark liner; omit redundant tube.

# Cabin, tapering in width toward the roof. Six-sided profile extrusion.
cab=[(-.75,1.308),(-.095,1.844),(.06,1.889),(1.95,1.889),(2.10,1.831),(2.185,1.29)]
verts=[]
for s in (-1,1):
    for y,z in cab:
        x=.955-(z-1.30)*.165
        verts.append((s*x,y,z))
n=len(cab);faces=[tuple(range(n-1,-1,-1)),tuple(range(n,n*2))]+[(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]
cabin=mesh('Cabin outer shell',verts,faces,'paint','H9_BodyPaint');bevel(cabin,.028,3)
box('Roof skin',(.0,1.005,1.872),(1.734,2.02,.083),'paint',.065,'H9_BodyPaint',4)

def side_surface(name,poly,s,material,group,offset=.006,bev=.008):
    v=[]
    for dx in (offset,offset+.009):
        for y,z in poly:v.append((s*(.955-(z-1.30)*.165+dx),y,z))
    n=len(poly);f=[tuple(range(n-1,-1,-1)),tuple(range(n,2*n))]+[(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]
    o=mesh(name,v,f,material,group)
    if bev:bevel(o,bev,1 if material=='trim' else 2)
    return o

window_polys=[ [(-.598,1.375),(-.054,1.804),(.078,1.82),(.601,1.82),(.601,1.375)],[(.673,1.375),(.673,1.82),(1.353,1.82),(1.37,1.375)],[(1.425,1.375),(1.414,1.82),(1.945,1.82),(2.02,1.757),(2.047,1.417),(2.013,1.375)] ]
for s in (-1,1):
    for idx,poly in enumerate(window_polys):
        side_surface('Window rubber border',poly,s,'trim','H9_Trim',.009,.014)
        cy=sum(y for y,z in poly)/len(poly);cz=sum(z for y,z in poly)/len(poly)
        inner=[(cy+(y-cy)*.937,cz+(z-cz)*.89) for y,z in poly]
        side_surface('Tinted side glazing',inner,s,'glass','H9_Glass',.022,.01)
    tube('Window sill',[(s*.96,-.635,1.326),(s*.96,1.95,1.326),(s*.945,2.073,1.34)],.015,'trim','H9_Trim',8)
    # Slim quarter window divider, door relief and restrained shallow shut-lines.
    for y in (.625,1.390):
        path=[(s*.981,y,1.31),(s*.979,y,.82),(s*.940,y+.008,.496)] if y<1 else [(s*.972,y,1.31),(s*.974,y,1.145)]
        tube('Door seam',path,.003,'trim','H9_Trim',6)
    tube('Front door shutline',[(s*.962,-.62,1.307),(s*.983,-.605,.95),(s*.954,-.535,.575)],.003,'trim','H9_Trim',6)
    for y in (.41,1.20):
        box('Handle recessed shadow',(s*.983,y,1.231),(.019,.239,.07),'trim',.025,'H9_Trim',4)
        box('Body colored handle',(s*1.004,y-.004,1.24),(.045,.207,.044),'paint',.018,'H9_BodyPaint',3)
    # Lower sculpted door highlight; tapered points avoid a generic rectangular slab.
    poly=[(-.48,.554),(-.35,.612),(.69,.606),(.805,.578),(.81,.54),(-.48,.523)]
    o=prism('Lower door sculpt',poly,'X',s*.958-.014,s*.958+.014,'paint','H9_BodyPaint',.022,3)
    # Side step with black caps and a narrow satin foot strip.
    box('Side step',(s*.969,-.02,.395),(.245,1.80,.068),'trim',.035,'H9_SideSteps',3)
    box('Step tread',(s*1.035,-.02,.431),(.095,1.70,.009),'rim',.004,'H9_SideSteps',2)
    for y in (-.57,.53):box('Step support',(s*.81,y,.365),(.23,.065,.065),'trim',.012,'H9_Chassis',2)
    # Mirror: stalk, painted cap, dark rear glass; simplified reference silhouette.
    tube('Mirror mounting stalk',[(s*.955,-.54,1.338),(s*1.077,-.53,1.394)],.038,'trim','H9_Trim',10)
    box('Mirror lower housing',(s*1.09,-.545,1.468),(.205,.209,.164),'trim',.046,'H9_Trim',4)
    box('Mirror paint cap',(s*1.098,-.572,1.50),(.206,.162,.115),'paint',.035,'H9_BodyPaint',4)
    box('Mirror glass',(s*1.10,-.431,1.476),(.142,.009,.098),'glass',.018,'H9_Glass',3)
    box('Mirror indicator',(s*1.104,-.658,1.47),(.144,.009,.013),'head',.006,'H9_Headlights',2)

# Windshield lies precisely on the sloped front plane, with a small thickness.
def windshield(name,w0,w1,z0,z1,material,group,offset):
    def y(z):return -.75+(z-1.308)/(.536)*.655-offset
    v=[(-w0,y(z0),z0),(w0,y(z0),z0),(w1,y(z1),z1),(-w1,y(z1),z1)]
    back=[(x,a+.009,z) for x,a,z in v]
    return mesh(name,v+back,[(3,2,1,0),(4,5,6,7),(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7)],material,group)
windshield('Windshield surround',.876,.796,1.352,1.816,'trim','H9_Trim',.018)
windshield('Dark windshield',.853,.776,1.378,1.797,'glass','H9_Glass',.026)
for x in (-.395,.385):tube('Wiper',[(x-.23,-.688,1.37),(x+.24,-.657,1.399)],.009,'trim','H9_Trim',6)

# Hood cap has its own mild crown and beveled edge.
hoodpoly=[(-.845,-2.27),(.845,-2.27),(.883,-2.05),(.869,-.765),(-.869,-.765),(-.883,-2.05)]
hood=prism('Hood skin',hoodpoly,'Z',1.314,1.366,'paint','H9_BodyPaint',.029,3)
for s in (-1,1):tube('Hood shoulder crease',[(s*.751,-2.205,1.365),(s*.762,-1.1,1.373),(s*.771,-.812,1.373)],.0055,'paint','H9_BodyPaint',6)

# The broad upright grille and circular DRL lamps define the H9 front.
box('Grille deep recess',(0,-2.327,1.063),(1.239,.056,.479),'trim',.033,'H9_Grille',4)
for k in range(5):
    z=.857+k*.101
    box('Horizontal grille bar',(0,-2.363,z),(1.198,.062,.035),'trim',.014,'H9_Grille',3)
    box('Bar fine metallic edge',(0,-2.396,z+.009),(1.12,.007,.006),'rim',.002,'H9_Grille',2)
for s in (-1,1):
    x=s*.763
    box('Square lamp frame',(x,-2.308,1.069),(.331,.109,.415),'rim',.040,'H9_Headlights',4)
    box('Square lamp pocket',(x,-2.369,1.069),(.297,.039,.38),'trim',.042,'H9_Headlights',5)
    # Circle in a softly rectangular housing, not generic rectangular LEDs.
    ring('Circular lamp bezel',[(-.007,.131),(.009,.131),(.018,.123),(.018,.115),(.008,.112),(-.007,.116)],(x,-2.397,1.073),'Y','rim','H9_Headlights',40)
    ring('Circular daytime light',[(-.001,.116),(.006,.119),(.010,.116),(.010,.107),(.004,.105),(-.001,.107)],(x,-2.409,1.073),'Y','head','H9_Headlights',40)
    box('Headlamp projector',(x,-2.415,1.07),(.11,.014,.052),'glass',.016,'H9_Headlights',3)
    box('Projector signature',(x,-2.425,1.067),(.086,.009,.020),'head',.007,'H9_Headlights',3)
    box('Headlamp bridge',(x,-2.418,1.055),(.20,.012,.011),'rim',.004,'H9_Headlights',2)

# Reference badge is restrained geometry; no registration text anywhere.
def textmesh(name,text,loc,size,material,group,rot=(pi/2,0,0),extrude=.001):
    c=bpy.data.curves.new(name,'FONT');c.body=text;c.align_x='CENTER';c.align_y='CENTER';c.size=size;c.extrude=extrude;c.offset=0 if name=='GWM spare badge' else .0007;c.resolution_u=2;c.space_character=1.13
    o=bpy.data.objects.new(name,c);sc.collection.objects.link(o);o.location=loc;o.rotation_euler=rot;c.materials.append(M[material])
    bpy.context.view_layer.objects.active=o;o.select_set(True);bpy.ops.object.convert(target='MESH');o.select_set(False)
    groups.setdefault(group,[]).append(o);return o
textmesh('HAVAL grille wordmark','HAVAL',(0,-2.415,1.105),.174,'rim','H9_Grille',extrude=.002)
box('Upper front bumper',(0,-2.351,.776),(1.965,.246,.135),'paint',.055,'H9_BodyPaint',4)
for s in (-1,1):
    x=s*.824
    box('Bumper corner',(x,-2.264,.582),(.343,.396,.333),'paint',.073,'H9_BodyPaint',4)
    box('Foglight inset',(x,-2.469,.678),(.231,.018,.071),'trim',.020,'H9_Trim',3)
    box('Foglight lens',(x+s*.056,-2.48,.679),(.057,.010,.027),'head',.011,'H9_Headlights',3)
box('Lower intake',(0,-2.352,.628),(1.244,.15,.164),'trim',.026,'H9_Grille',3)
for z in (.595,.64):box('Lower intake rail',(0,-2.436,z),(1.13,.015,.012),'trim',.005,'H9_Grille',2)
for x in (-.39,0,.39):box('Lower intake upright',(x,-2.434,.627),(.035,.025,.117),'trim',.005,'H9_Grille',2)
box('Front skid silhouette',(0,-2.215,.435),(1.29,.397,.115),'trim',.053,'H9_Chassis',4)

# Rear glazing, swing tailgate, distinct stacked vertical tail lamps and spare cover.
box('Rear glass surround',(0,2.143,1.58),(1.692,.062,.442),'trim',.067,'H9_Trim',5)
box('Rear tinted glass',(0,2.18,1.596),(1.596,.016,.365),'glass',.048,'H9_Glass',4)
box('Tailgate face',(0,2.223,1.015),(1.539,.062,.645),'paint',.043,'H9_BodyPaint',4)
box('Tailgate side handle',(.585,2.267,1.074),(.061,.031,.218),'trim',.027,'H9_Trim',4)
box('Rear bumper',(0,2.226,.545),(1.951,.257,.243),'paint',.054,'H9_BodyPaint',4)
box('Rear step protector',(0,2.232,.677),(1.405,.231,.027),'trim',.014,'H9_Trim',3)
box('Rear lower valance',(0,2.192,.402),(1.62,.202,.092),'trim',.031,'H9_Chassis',3)
for s in (-1,1):
    x=s*.848
    box('Tall rear lamp pocket',(x,2.193,1.09),(.184,.11,.602),'trim',.073,'H9_Trim',5)
    for z in (.964,1.215):
        box('Rear stacked red lens',(x,2.254,z),(.125,.031,.177),'tail',.044,'H9_Taillights',5)
        # Raised perimeter, dark inset, lower red light segments.
        box('Rear lens inset',(x,2.273,z),(.070,.009,.11),'tail',.027,'H9_Taillights',4)
        for zz in (-.027,.006):box('Rear lens segment',(x,2.28,z+zz),(.065,.006,.013),'tail',.004,'H9_Taillights',2)
    box('Rear bumper reflector',(s*.856,2.36,.593),(.134,.012,.042),'tail',.012,'H9_Taillights',3)
box('High brake lamp',(0,2.116,1.833),(.39,.035,.024),'tail',.010,'H9_Taillights',3)
tube('Rear wiper',[(.04,2.201,1.473),(.455,2.201,1.46)],.01,'trim','H9_Trim',6)
box('Spare wheel dark base',(-.12,2.305,1.08),(.836,.242,.798),'trim',.164,'H9_SpareWheelCover',7)
box('Spare wheel painted cover',(-.12,2.474,1.09),(.80,.275,.756),'paint',.164,'H9_SpareWheelCover',8)
box('Spare central badge plinth',(-.12,2.615,1.16),(.501,.02,.141),'trim',.038,'H9_SpareWheelCover',4)
textmesh('GWM spare badge','G W M',(-.12,2.63,1.16),.065,'rim','H9_SpareWheelCover',(pi/2,0,pi),.001)
textmesh('Rear H9 badge','H9',(-.68,2.266,.797),.043,'rim','H9_Trim',(pi/2,0,pi),.0008)

# Raised side roof rails and mounting feet. Keep center open, not a roof rack.
for s in (-1,1):
    x=s*.763
    path=[(x,-.048,1.909),(x,.067,1.978),(x,.198,1.986),(x,1.827,1.977),(x,1.954,1.93)]
    tube('Roof side rail',path,.029,'trim','H9_RoofRails',10)
    for y in (.127,1.034,1.847):box('Rail foot',(x,y,1.924),(.083,.14,.06),'trim',.02,'H9_RoofRails',3)
# Underfloor only: no drivetrain or detailed interior.
box('Underfloor',(0,.08,.362),(.93,3.925,.139),'trim',.035,'H9_Chassis',3)

# Exactly four functional wheels. Wheel geometry is centred around the X axle.
def wheel(name,s,y,steer=False):
    group=name
    tire_profile=[(-.139,.266),(-.147,.321),(-.133,.370),(-.110,.398),(-.078,.408),(.078,.408),(.110,.398),(.133,.370),(.147,.321),(.139,.266),(.103,.251),(-.103,.251)]
    ring('Tire casing',tire_profile,(0,0,0),'X','rubber',group,48)
    # A few broad shallow shoulder sipes: legible and cheap, no modeled branding.
    for side in (-1,1):
        ring('Sidewall bead',[(side*.144,.304),(side*.148,.302),(side*.149,.299),(side*.145,.297)],(0,0,0),'X','rubber',group,24)
    # Alloy barrel, outer rim lip and ten split spokes reflect the reference rim.
    rimprof=[(-.125,.231),(-.129,.251),(.129,.251),(.147,.244),(.150,.229),(.139,.219),(.113,.222),(-.112,.222)]
    ring('Rim barrel',rimprof,(0,0,0),'X','rim',group,48)
    ring('Inset brake silhouette',[(-.045,.001),(-.045,.194),(-.027,.194),(-.027,.001)],(0,0,0),'X','trim',group,32)
    for k in range(10):
        a=k*2*pi/10
        poly=[]
        # Slight directional sweep rather than simple rectangular bars.
        for r,t in [(.052,a-.22),(.180,a-.12),(.231,a-.080),(.235,a+.082),(.198,a+.14),(.065,a+.22)]:poly.append((r*cos(t),r*sin(t)))
        prism('Swept alloy spoke',poly,'X',.098,.141,'rim',group,.007,1)
    ring('Hub cap',[(.09,.001),(.09,.061),(.148,.061),(.154,.049),(.154,.001)],(0,0,0),'X','rim',group,24)
    ring('Dark center insert',[(.154,.001),(.154,.038),(.159,.038),(.159,.001)],(0,0,0),'X','trim',group,24)
    # Five efficient lug recesses only, each one simple prism.
    for k in range(5):
        a=k*2*pi/5
        yy=.079*cos(a);zz=.079*sin(a)
        p=[(yy+.010*cos(j*2*pi/6),zz+.010*sin(j*2*pi/6)) for j in range(6)]
        prism('Wheel lug recess',p,'X',.140,.146,'trim',group)
    parts=groups.pop(group)
    for o in bpy.context.selected_objects:o.select_set(False)
    for o in parts:o.select_set(True)
    bpy.context.view_layer.objects.active=parts[0];bpy.ops.object.join();o=bpy.context.object;o.name=name
    o.data.transform(Matrix.Diagonal((1,1.04,1.04,1)))
    # Reflect the mesh, not the object transform, for the right side.
    if s<0:
        o.data.transform(Matrix.Diagonal((-1,1,1,1)))
        bm=bmesh.new();bm.from_mesh(o.data);bmesh.ops.recalc_face_normals(bm,faces=bm.faces);bm.to_mesh(o.data);bm.free()
    if steer:
        p=empty(name+'_SteeringPivot',(s*.858,y,.42432),root)
        p['steer_axis_blender']='Z';p['steer_axis_glTF']='Y';o.parent=p;o.location=(0,0,0)
    else:o.parent=root;o.location=(s*.858,y,.42432)
    o['spin_axis']='X';o['radius_m']=.42432;o['road_wheel']=True
    return o

wheel('Wheel_FL',1,-1.44,True);wheel('Wheel_FR',-1,-1.44,True)
wheel('Wheel_RL',1,1.41);wheel('Wheel_RR',-1,1.41)

# Blank plates: a physical mounting body and a clean 0..1 front-facing UV surface.
def plate(which,y,z,front=True):
    sign=-1 if front else 1
    p=box('H9_LicensePlate_'+which,(0,y,z),(.522,.016,.130),'plate',.007,None,3)
    p.parent=root
    frame=box('H9_LicensePlateFrame_'+which,(0,y-sign*.014,z),(.552,.031,.156),'trim',.013,None,3);frame.parent=root
    ww=.249;hh=.055;yy=y+sign*.010
    # Surface vertex order is viewed from outside: left, right, top right, top left.
    xx=[-ww,ww] if front else [ww,-ww]
    v=[(xx[0],yy,z-hh),(xx[1],yy,z-hh),(xx[1],yy,z+hh),(xx[0],yy,z+hh)]
    me=bpy.data.meshes.new('LicensePlateUV_'+which);me.from_pydata(v,[],[(0,1,2,3)]);me.update()
    o=bpy.data.objects.new('LicensePlateSurface_'+which,me);sc.collection.objects.link(o);o.parent=p
    # Parenting preserves an explicit identity local transform after recentering vertices.
    for vert in me.vertices:vert.co-=p.location
    me.materials.append(M['plate']);uv=me.uv_layers.new(name='PlateUV')
    uvs=[(0,0),(1,0),(1,1),(0,1)]
    for poly in me.polygons:
        for li in poly.loop_indices:uv.data[li].uv=uvs[me.loops[li].vertex_index]
    o['dynamic_texture']=True;o['canvas_texture_flipY']=False;o['recommended_canvas']='1024x226 (plate aspect ratio)'
plate('Front',-2.513,.779,True)
plate('Rear',2.374,.557,False)

# Consolidate semantic components. Wheels and plate surfaces remain independent.
for name,parts in groups.items():
    parts=[o for o in parts if o.name in bpy.data.objects]
    if not parts:continue
    bpy.ops.object.select_all(action='DESELECT')
    for o in parts:o.select_set(True)
    bpy.context.view_layer.objects.active=parts[0];bpy.ops.object.join();o=bpy.context.object;o.name=name
    # Keep geometry in vehicle coordinates, reset parent part origins to root.
    world=o.matrix_world.copy();o.data.transform(world);o.matrix_world=Matrix.Identity(4);o.parent=root
    o.rotation_euler=(0,0,0);o.scale=(1,1,1)
    # Materials introduced by parts share existing datablocks; slots are reduced by join.
    o.data.validate(verbose=False)

# Weld extruded badge boundaries and remove zero-length bevel edges. Plate UV quads remain intact.
for obj in sc.objects:
    if obj.type!='MESH' or obj.name.startswith(('LicensePlateSurface_','Wheel_')):continue
    bm=bmesh.new();bm.from_mesh(obj.data)
    bmesh.ops.remove_doubles(bm,verts=list(bm.verts),dist=.000001)
    bmesh.ops.dissolve_degenerate(bm,edges=list(bm.edges),dist=.000001)
    bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces))
    bm.to_mesh(obj.data);bm.free();obj.data.update()
    if not obj.name.startswith('Wheel_'):
        mod=obj.modifiers.new('Final weighted normals','WEIGHTED_NORMAL');mod.keep_sharp=True;apply(obj,mod)

# Ensure no accidental scale/rotation on wheels; select only the vehicle by default.
for o in sc.objects:
    if o.type=='MESH':
        o.data.calc_loop_triangles()
        if o.name.startswith('Wheel_'):assert all(abs(a-1)<1e-6 for a in o.scale)

# Neutral temporary studio. Removed from the final delivery GLB after renders.
world=bpy.data.worlds.new('Inspection world') if not sc.world else sc.world
sc.world=world;world.use_nodes=True;world.node_tree.nodes['Background'].inputs['Color'].default_value=(.32,.36,.41,1)
world.node_tree.nodes['Background'].inputs['Strength'].default_value=.40
def area(name,loc,power,size):
    data=bpy.data.lights.new(name,'AREA');data.energy=power;data.shape='DISK';data.size=size
    o=bpy.data.objects.new(name,data);sc.collection.objects.link(o);o.location=loc;o.rotation_euler=(Vector((0,0,1))-o.location).to_track_quat('-Z','Y').to_euler();return o
area('Studio_Key',(4,-4,7),900,5)
area('Studio_Fill',(-4,-1,4),650,4)
area('Studio_Rim',(1,5,5),850,4)
camdata=bpy.data.cameras.new('Inspection camera');cam=bpy.data.objects.new('Inspection camera',camdata);sc.collection.objects.link(cam)
cam.location=(6.0,-8.0,3.4);cam.rotation_euler=(Vector((0,0,1.0))-cam.location).to_track_quat('-Z','Y').to_euler();camdata.type='ORTHO';camdata.ortho_scale=6.5;sc.camera=cam
sc.render.engine='BLENDER_EEVEE';sc.render.resolution_x=1200;sc.render.resolution_y=900;sc.render.resolution_percentage=100
sc.render.image_settings.file_format='PNG';sc.render.film_transparent=False
if hasattr(sc,'eevee') and hasattr(sc.eevee,'taa_render_samples'):sc.eevee.taa_render_samples=24
try:sc.view_settings.view_transform='Khronos PBR Neutral'
except:pass
bpy.ops.object.select_all(action='DESELECT');root.select_set(True);bpy.context.view_layer.objects.active=root
for me in list(bpy.data.meshes):
    if me.users==0:bpy.data.meshes.remove(me)
for c in list(bpy.data.curves):
    if c.users==0:bpy.data.curves.remove(c)
stats={o.name:len(o.data.loop_triangles) for o in sc.objects if o.type=='MESH'}
result={'triangles':sum(stats.values()),'per_mesh':stats,'materials':list(M.keys()),'wheels':[o.name for o in sc.objects if o.get('road_wheel')],'axis':'Blender -Y forward / GLB +Z forward; GLB +Y up; local X wheel spin','dimensions_approx_m':{'length':5.16,'body_width':2.032,'roof_rails_height':2.015},'source':'all geometry new, constructed from photographs'}
